homeassistant:
  name: HHZ
  latitude: 48.679763
  longitude: 8.999435
  elevation: 410
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customized.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

logger:
  default: critical
  logs:
    homeassistant.components: info

recorder:
  purge_days: 7

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

light:
  platform: hue
  
#Switches on Dashboard
input_boolean:
  stopwatch:
    name: Lecture
    initial: off
  timerdummy:
    name: timerdummy
    initial: off
  breakrequest:
    name: breakrequest
    initial: off

mqtt:
  broker: localhost
  client_id: [CLIENT ID]
  username: [USERNAME]
  password: [PASSWORD]

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
device_tracker: !include device_tracker.yaml

